import { describe, expect, it } from 'vitest';
import {
  assignComponentClassNames,
  generateComponentCss,
} from '../src/generator/cssGenerator.js';
import type { ClassCombination } from '../src/parser/types.js';

function combo(
  classes: string[],
  occurrences: number,
): ClassCombination {
  return {
    normalized: classes.sort().join(' '),
    classes: [...classes].sort(),
    occurrences,
    suggestion: `.${classes.join('-')}`,
    locations: [],
  };
}

describe('cssGenerator', () => {
  it('assigns unique class names', () => {
    const components = assignComponentClassNames([
      combo(['flex', 'p-4'], 8),
      combo(['flex', 'gap-2'], 6),
    ]);

    expect(components).toHaveLength(2);
    expect(components[0]?.className).toBeTruthy();
    expect(components[1]?.className).toBeTruthy();
    expect(components[0]?.className).not.toBe(components[1]?.className);
  });

  it('generates @layer components CSS with @apply', () => {
    const { css, components } = generateComponentCss({
      sourcePath: './src',
      combinations: [
        combo(['flex', 'items-center', 'justify-between', 'p-4'], 8),
      ],
    });

    expect(components).toHaveLength(1);
    expect(components[0]?.className).toBe('twu-page-header');
    expect(css).toContain('@layer components');
    expect(css).toContain('@apply flex items-center justify-between p-4;');
    expect(css).toContain('.twu-page-header');
    expect(css).toContain('Generated by tailwind-unwind');
    expect(css).toContain('Class prefix: twu-');
  });

  it('supports custom prefix', () => {
    const { components } = generateComponentCss({
      sourcePath: './src',
      combinations: [combo(['flex', 'p-4'], 4)],
      prefix: 'app-',
    });

    expect(components[0]?.className).toMatch(/^app-/);
  });

  it('uses custom names from config', () => {
    const { components } = generateComponentCss({
      sourcePath: './src',
      combinations: [
        combo(['flex', 'items-center', 'justify-between', 'p-4'], 8),
      ],
      names: {
        'flex items-center justify-between p-4': 'app-header',
      },
    });

    expect(components[0]?.className).toBe('twu-app-header');
  });

  it('returns helpful comment when no combinations found', () => {
    const { css, components } = generateComponentCss({
      sourcePath: './src',
      combinations: [],
    });

    expect(components).toHaveLength(0);
    expect(css).toContain('No frequent class combinations found');
  });
});
