import { suggestClassName } from '../analyzer/suggestions.js';
import type { ClassCombination } from '../parser/types.js';
import { normalizeClassPrefix, withClassPrefix } from './classPrefix.js';

export interface GeneratedComponent {
  className: string;
  classes: string[];
  occurrences: number;
}

export interface CssGeneratorOptions {
  sourcePath: string;
  combinations: ClassCombination[];
  prefix?: string;
}

export interface CssGeneratorResult {
  css: string;
  components: GeneratedComponent[];
}

export interface AssignClassNamesOptions {
  prefix?: string;
}

/** Assign unique, prefixed component class names. */
export function assignComponentClassNames(
  combinations: ClassCombination[],
  options: AssignClassNamesOptions = {},
): GeneratedComponent[] {
  const used = new Set<string>();

  return combinations.map((combo) => {
    const base = suggestClassName(combo.classes);
    let className = withClassPrefix(base, options.prefix);
    let suffix = 2;

    while (used.has(className)) {
      className = withClassPrefix(`${base}-${suffix}`, options.prefix);
      suffix += 1;
    }

    used.add(className);

    return {
      className,
      classes: combo.classes,
      occurrences: combo.occurrences,
    };
  });
}

/**
 * Build a Tailwind CSS file with @layer components and @apply rules
 * for the most frequent class combinations.
 */
export function generateComponentCss(
  options: CssGeneratorOptions,
): CssGeneratorResult {
  const components = assignComponentClassNames(options.combinations, {
    prefix: options.prefix,
  });
  const timestamp = new Date().toISOString();
  const classPrefix = normalizeClassPrefix(options.prefix);

  const header = [
    '/**',
    ' * Generated by tailwind-unwind',
    ` * Source: ${options.sourcePath}`,
    ` * Generated at: ${timestamp}`,
    ` * Class prefix: ${classPrefix}`,
    ' */',
    '',
  ].join('\n');

  if (components.length === 0) {
    return {
      css: `${header}\n/* No frequent class combinations found. Try lowering --min-occurrences. */\n`,
      components: [],
    };
  }

  const rules = components
    .map((component) => {
      const applyClasses = component.classes.join(' ');
      return `  .${component.className} {\n    @apply ${applyClasses};\n  }`;
    })
    .join('\n\n');

  const css = `${header}\n@layer components {\n${rules}\n}\n`;

  return { css, components };
}
